### ISSUE TITLE
cv2.ximgproc

### ISSUE THREAD

**Issue by drtentaculous** [p1atdev/stable-diffusion-webui-adverse-cleaner-tab#2]
hi, i can't run extension a of cv2.ximgproc.

I tried to reinstall it using these commands but it didn't work.

pip uninstall opencv-contrib-python opencv-python

pip install opencv-contrib-python

log :

Error running install.py for extension extensions\stable-diffusion-webui-adverse-cleaner-tab.
Command: "E:\ia\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\stable-diffusion-webui-adverse-cleaner-tab\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "E:\ia\stable-diffusion-webui\extensions\stable-diffusion-webui-adverse-cleaner-tab\install.py", line 3, in <module>
    if not launch.is_installed("cv2.ximgproc"):
  File "E:\ia\stable-diffusion-webui\launch.py", line 127, in is_installed
    spec = importlib.util.find_spec(package)
  File "C:\Python310\lib\importlib\util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: cv2.ximgproc.__spec__ is None

**Comment by drtentaculous** [comment]
I managed to fix it by removing --user in the install.py file

**Comment by Quansheng2021** [comment]
> I managed to fix it by removing --user in the install.py file

indeed

**Comment by p1atdev** [comment]
Very strange...
In my environment, another error occurred when I didn't have --user and I couldn't install opencv-contrib-python

**Comment by p1atdev** [comment]
~~ah, I figured it out. When venv is enabled, the --user flag is not needed~~

I finally found the problem. During webui running it uses opencv, so this extension can't modify opencv package and install any additional module of opencv.

So we need to install opencv-contrib-python by hand when webui is not running.

**Comment by Dawgmastah** [comment]
Did do that... but it says already satisfied, still wont work in webui

(venv) X:\STABLEDIFFUSION\AUTOMATIC11111>pip install opencv-contrib-python
Requirement already satisfied: opencv-contrib-python in x:\stablediffusion\automatic11111\venv\lib\site-packages (4.9.0.80)
Requirement already satisfied: numpy>=1.17.3 in x:\stablediffusion\automatic11111\venv\lib\site-packages (from opencv-contrib-python) (1.23.5)
