### ISSUE TITLE
 has new error,  git pull the S-D-webui new version , at 3/25

### ISSUE THREAD

**Issue by Quansheng2021** [p1atdev/stable-diffusion-webui-adverse-cleaner-tab#3]
i have git pull the S-D-webui new version , at 3/25

and start S-D-webui  has error,
how to solve this error:

Error executing callback ui_tabs_callback for D:\stable-diffusion-webui\extensions\stable-diffusion-webui-adverse-cleaner-tab\scripts\main.py
Traceback (most recent call last):
File "D:\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
res += c.callback() or []
File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-adverse-cleaner-tab\scripts\main.py", line 197, in on_ui_tabs
start_btn.click(
File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\events.py", line 129, in __call__
dep, dep_index = self.trigger.set_event_trigger(
File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 195, in set_event_trigger
check_function_inputs_match(fn, inputs, inputs_as_dict)
File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 940, in check_function_inputs_match
if not is_special_typed_parameter(name):
File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 929, in is_special_typed_parameter
is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class

**Comment by p1atdev** [comment]
fixed at commit hash f6208a3

related: https://github.com/gradio-app/gradio/issues/3514
